# Ruby
# Package your Ruby application.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.4.2'

- script: sudo apt-get install -y qt5-default
- script: sudo apt-get install -y libqt5webkit5-dev
- script: sudo apt-get install -y gstreamer1.0-plugins-base
- script: sudo apt-get install -y gstreamer1.0-tools gstreamer1.0-x

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'



- script: bundle exec rake
  displayName: 'bundle exec rake'
