development:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] || 'localhost' %>:6379/3

test:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] || 'localhost' %>:6379/2

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_HOST'] || 'localhost' %>:6379/1